#pragma config(Sensor, port7,  TopButton,      sensorVexIQ_Touch)
#pragma config(Sensor, port8,  BottomButton,   sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          LeftDriveMotor, tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor2,          MantisLeft,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor4,          RightArmMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor10,         LeftArmMotor,  tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11,         MantisRight,   tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         RightDriveMotor, tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void moveArm(float timeToMove, int speed){
	setMotor(RightArmMotor, speed);
	setMotor(LeftArmMotor, speed);
	wait(timeToMove, seconds);
	stopAllMotors();
}


void raiseArmTop(){
	repeatUntil (getBumperValue(TopButton) == 1)
	{
		setMotor(RightArmMotor,100);
		setMotor(LeftArmMotor,100);
	}

}
void getYellowHubGriffin(){
	repeatUntil(getBumperValue(TopButton) == 1)
	{
		setMotor(RightArmMotor,100);
		setMotor(LeftArmMotor,100);
	}
	turnLeft(90,degrees,100);
	moveArm(0.75,-100);
	forward(1.2,seconds,60);
	moveArm(0.8,100);
	backward(0.6,seconds,100);

}
void getYellowHubGriffinOP(){
	repeatUntil(getBumperValue(TopButton) == 1)
	{
		setMotor(RightArmMotor,100);
		setMotor(LeftArmMotor,100);
	}
	turnRight(90,degrees,100);
	moveArm(0.75,-100);
	forward(1.2,seconds,60);
	moveArm(0.8,100);
	backward(0.35,seconds,100);

}





void runProgram(){
		//move mantis arms out of the way
	moveMotor(MantisLeft,100,degrees,50);
	moveMotor(MantisRight,100,degrees,50);
	//get yellow hub
	getYellowHubGriffinOP();
	//Cross Field
	turnLeft(348,degrees,100);
	forward(2.2,seconds,100);
	//Push orange hubs into score zone
	turnRight(122,degrees,50);
	forward(1.1,seconds,100);
	turnRight(150,degrees,25);
	moveMotor(MantisLeft,-100,degrees,50);
	forward(1.6,seconds,100);
	moveMotor(MantisRight,-100,degrees,50);
	turnLeft(122,degrees,100);
	moveMotor(MantisLeft,100,degrees,50);
	moveMotor(MantisRight,100,degrees,50);
	forward(0.8,seconds,100);
	//Stack Yellow Hub
	backward(0.5,seconds,100);
	moveArm(1.7,-80);
	moveArm(0.2,60);
	backward(0.5,seconds,100);
	//Get arms in down position
	moveMotor(MantisLeft,100,degrees,-50);
	moveMotor(MantisRight,100,degrees,-50);

}

void runSecondProgram(){
		//move mantis arms out of the way
	moveMotor(MantisLeft,100,degrees,50);
	moveMotor(MantisRight,100,degrees,50);
	//get yellow hub
	getYellowHubGriffin();
	//get orange hubs
	turnRight(90,degrees,100);
	moveArm(1,-100);
	forward(1.6,seconds,100);
	moveMotor(MantisLeft,100,degrees,-50);
	//move to score zone
	backward(2,seconds,100);
	turnLeft(340,degrees,100);
	forward(1.9,seconds,100);
	backward(0.2,seconds,100);
	moveArm(0.3,80);
	//stack yellow
	moveMotor(MantisLeft,100,degrees,50);
	backward(0.8,seconds,100);
	turnRight(150,degrees,100);
	forward(0.4,seconds,100);
	turnLeft(230,degrees,100);
	forward(1,seconds,50);
	moveArm(0.9,-80);
	moveArm(0.4,60);
	backward(0.7,seconds,100);
	//hang
	turnRight(200,degrees,100);
	backward(2,seconds,100);
	raiseArmTop();
	moveMotor(MantisLeft,100,degrees,-50);
	moveMotor(MantisRight,100,degrees,-50);
	turnRight(105,degrees,100);
	backward(0.7,seconds,100);

	forward(1.5,seconds,100);
	moveArm(3.5,-100);

		repeat(forever){
		stopAllMotors();
	}
}

task main()
{
	waitUntil(getBumperValue(TopButton) == 1);
  runProgram();
  waitUntil(getBumperValue(TopButton) == 1);
  runSecondProgram();
}
