#pragma config(Sensor, port7,  TopButton,      sensorVexIQ_Touch)
#pragma config(Sensor, port8,  BottomButton,   sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          LeftDriveMotor, tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor2,          MantisLeft,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor4,          RightArmMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor10,         LeftArmMotor,  tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11,         MantisRight,   tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         RightDriveMotor, tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void moveArm(float timeToMove, int speed){
	setMotor(RightArmMotor, speed);
	setMotor(LeftArmMotor, speed);
	wait(timeToMove, seconds);
	stopAllMotors();
}
void getYellowHub(){
	repeatUntil(getBumperValue(TopButton) == 1)
	{
		setMotor(RightArmMotor,100);
		setMotor(LeftArmMotor,100);
	}
	moveArm(0.7,-100);
	backward(1,seconds,100);
	forward(1,seconds,60);
	moveArm(0.8,100);
	backward(1,seconds,100);

}
void raiseArmTop(){
	repeatUntil (getBumperValue(TopButton) == 1)
	{
		setMotor(RightArmMotor,100);
		setMotor(LeftArmMotor,100);
	}
}
void lowerArmBottom(){
	repeatUntil (getBumperValue(BottomButton) == 1)
	{
		setMotor(RightArmMotor,-100);
		setMotor(LeftArmMotor,-100);
	}
	stopAllMotors();
}
void placeHubDown(){
	repeatUntil(getBumperValue(BottomButton) == 1)
	{
		setMotor(RightArmMotor,-100);
		setMotor(LeftArmMotor,-100);
	}

	stopAllMotors();

}

void runProgram(){
	//move mantis arms out of the way
	moveMotor(MantisLeft,100,degrees,50);
	moveMotor(MantisRight,100,degrees,50);
	//get yellow hub
	turnLeft(-290,degrees,100);
	forward(0.98,seconds,100);
	turnRight(290,degrees,100);
	getYellowHub();
	//place yellow hub
	turnLeft(-290,degrees,100);
	forward(0.95,seconds,100);
	placeHubDown();
	//get to orange hub
	turnLeft(-95,degrees,100);
	backward(0.6, seconds, 100);
	turnRight(95,degrees,100);
	raiseArmTop();
	turnRight(90,degrees,100);
	forward(1,seconds,100);
	//score the orange hubs
	turnRight(110,degrees,100);
	forward(1.6,seconds,100);
	turnLeft(150,degrees,100);
	forward(0.1,seconds,100);
	//getting to hang possition
	backward(0.8,seconds,100);
	moveArm(0.5,-100);

}

void runSecondProgram(){
	//move mantis arms out of the way
	//moveMotor(MantisLeft,100,degrees,50);
	//moveMotor(MantisRight,100,degrees,50);
	//get yellow hub
  lowerArmBottom();
	turnRight(-290,degrees,100);
	forward(0.9,seconds,100);
	turnLeft(-290,degrees,100);
	getYellowHub();
	turnLeft(290,degrees,100);
	forward(3,seconds,100);
	moveArm(0.8,-100);
	turnRight(130,degrees,100);
	forward(2.3,seconds,100);
	moveArm(0.5,-100);
	//getting to hang possition
	backward(0.2,seconds,100);
	turnRight(92,degrees,100);
	backward(2.4,seconds,100);
	turnLeft(230,degrees,100);
	backward(1.5,seconds,100);
	turnRight(290,degrees,100);
	backward(0.7,seconds,100);
	//hanging
	moveMotor(MantisLeft,-100,degrees,50);
	moveMotor(MantisRight,-100,degrees,50);
	raiseArmTop();
	forward(1.5,seconds,100);
	moveArm(3.5,-100);

		repeat(forever){
		stopAllMotors();
	}
}

task main()
{
	waitUntil(getBumperValue(TopButton) == 1);
  runProgram();
  waitUntil(getBumperValue(TopButton) == 1);
  runSecondProgram();
}
